/go2_joystick_actions_node:
  ros__parameters:
    joystick_actions:
      buttons:
#        0:
#          sequence:
#            - StandUp
#            - BalanceStand
#        1:
#          command: StandDown
        2:
          command: "BackFlip"
#          parameter: '{ "data": true}'
#          sequence:
#            - BalanceStand
#            - BackFlip
        3:
          sequence:
            - BalanceStand
            - FrontFlip
        4:
          sequence:
            - BalanceStand
            - LeftFlip
