/go2_joystick_actions_node:
  ros__parameters:
    joystick_actions:
      buttons:
        2:
          command: "BackFlip"
          parameter: '{ "data": true}'
        3:
          command: "FrontFlip"
          parameter: '{ "data": true}'
        4:
          command: "LeftFlip"
          parameter: '{ "data": true}'
        5:
          command: "RightFlip"
          parameter: '{ "data": true}'
